title: RG Hamburg
description: Radsport-Gemeinschaft Hamburg von 1893 e.V.
lang: de
baseurl: ""
url: "https://rg-hamburg.github.io"

markdown: kramdown
permalink: pretty

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      permalink: /aktuelles/:year/:slug/

exclude:
  - docker-compose.yaml
  - documentation/
  - README.md
  - AGENTS.md
  - .github
  - .claude
  - .vscode
